spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://rpi4:3306/jpa}
    username: ${JDBC_DATABASE_USERNAME:mysql}
    password: ${JDBC_DATABASE_PASSWORD:Welcome1}
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
#      hibernate.format_sql: true
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        format_sql: true
springdoc:
  pathsToMatch: /api/**
logging:
  level:
    org.springframework: INFO